services:
  sql-server-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data-volume:/var/opt/mssql
volumes:
  sql-server-data-volume:
