services:
  sql-server-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data-volume:/var/opt/mssql
  mitm-proxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8080:8080"
      - "8081:8081"
    command: "mitmweb --web-host 0.0.0.0"
    volumes:
      - mitm-certs-volume:/home/mitmproxy/.mitmproxy
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  sql-server-data-volume:
  mitm-certs-volume:
