ALTER SESSION SET container=XEPDB1;
CREATE USER "TESTUSER1" IDENTIFIED BY "y0urStr0ngPassw0rd"
   DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE,
   CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER,
     CREATE TYPE, CREATE MATERIALIZED VIEW TO "TESTUSER1";